{
 "title": "Rsyslog",
 "description": "Prometheus Rsyslog exporter metrics.",
 "tags": [
  "prometheus",
  "rsyslog"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "database", "label": "database", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(rsyslog_exporter_up,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Core action",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rsyslog - processed",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rsyslog_action_processed{}[30m])) by (instance, name) > 0",
     "legendFormat": "{{ instance }}-{{ name }}"
    }
   ]
  },
  {
   "title": "Rsyslog - suspended",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rsyslog_action_suspended{}[30m])) by (instance, name)",
     "legendFormat": "{{ instance }}-{{ name }}"
    }
   ]
  },
  {
   "title": "Rsyslog - resumed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rsyslog_action_resumed{}[30m])) by (instance, name)",
     "legendFormat": "{{ instance }}-{{ name }}"
    }
   ]
  },
  {
   "title": "Rsyslog - suspended_duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rsyslog_action_suspended_duration{}[30m])) by (instance, name)",
     "legendFormat": "{{ instance }}-{{ name }}"
    }
   ]
  },
  {
   "title": "Rsyslog - failed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rsyslog_action_failed{}[30m])) by (instance, name)",
     "legendFormat": "{{ instance }}-{{ name }}"
    }
   ]
  },
  {
   "title": "Core queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rsyslog - enqueued",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rsyslog_queue_enqueued{}[30m])) by (instance, name) > 0",
     "legendFormat": "{{ instance }}-{{ name }}"
    }
   ]
  },
  {
   "title": "Rsyslog - full queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rsyslog_queue_full{}[30m])) by (instance, name)",
     "legendFormat": "{{ instance }}-{{ name }}"
    }
   ]
  },
  {
   "title": "Rsyslog - maxqsize",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rsyslog_queue_max_size{}[30m])) by (instance, name)",
     "legendFormat": "{{ instance }}-{{ name }}"
    }
   ]
  },
  {
   "title": "Rsyslog - discarded_full",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rsyslog_queue_discarded_full{}[30m])) by (instance, name)",
     "legendFormat": "{{ instance }}-{{ name }}"
    }
   ]
  },
  {
   "title": "Rsyslog - discarded_nf",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rsyslog_queue_discarded_not_full{}[30m])) by (instance, name)",
     "legendFormat": "{{ instance }}-{{ name }}"
    }
   ]
  }
 ]
}